const jsCommands = [
    'var',
    'const',
    'let',
    '[]',
    'concat',
    'indexOf',
    'join',
    'lastIndexOf',
    'pop',
    'push',
    'reverse',
    'shift',
    'slice',
    'sort',
    'splice',
    'toString',
    'unshift',
    '==',
    '===',
    '!=',
    '!==',
    '<=',
    '>=',
    '&&',
    '||',
    '<<',
    '>>',
    '>>>',
    'alert',
    'confirm',
    'console.log',
    'document.write',
    'prompt',
    'decodeURI',
    'decodeURIComponent',
    'encodeURI',
    'encodeURIComponent',
    'eval',
    'isFinite',
    'isNaN',
    'Number',
    'parseFloat',
    'parseInt',
    'for',
    'while',
    'do while',
    'break',
    'continue',
    'if',
    'else',
    'charAt',
    'charCodeAt',
    'fromCharCode',
    'match',
    'replace',
    'search',
    'split',
    'substr',
    'substring',
    'toLowerCase',
    'toUpperCase',
    'toExponential',
    'toFixed',
    'toPrecision',
    'valueOf',
    ':help',
    ':history',
    ':clear',
    // No MATH methods
    // No Date methods
    // No DOM methods
    // No Browser props
    // No Events
    // No Errors
    // https://websitesetup.org/wp-content/uploads/2020/09/Javascript-Cheat-Sheet.pdf
]

export default jsCommands